import { Injectable } from '@nestjs/common';
import { AssignmentsService } from '../../../assignments/assignments.service';
import {
  ToolHandlerKey,
  AgentToolExecutionContext,
  AGENT_ERRORS,
  AgentHandlerResult,
  ReconciliationResult,
} from '../agent-types';
import { AgentToolHandler } from './agent-tool-handler.interface';

export interface CreateAssignmentArgs {
  classId: string;
  subjectId: string;
  topic: string;
  description?: string;
  dueDate?: string;
  totalMarks?: number;
}

@Injectable()
export class CreateAssignmentAgentHandler implements AgentToolHandler<
  CreateAssignmentArgs,
  AgentHandlerResult
> {
  readonly key = ToolHandlerKey.CREATE_ASSIGNMENT;

  constructor(private readonly assignmentsService: AssignmentsService) {}

  async execute(
    context: AgentToolExecutionContext,
    args: CreateAssignmentArgs,
  ): Promise<AgentHandlerResult> {
    // Resolve staff profile via domain service AssignmentsService
    const staff = await this.assignmentsService.getStaffProfileByUserId(
      context.schoolId,
      context.userId,
    );
    if (!staff) {
      throw new Error('Teacher staff profile not found in this school');
    }

    const dueDateObj = args.dueDate
      ? new Date(args.dueDate)
      : new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);

    // Delegate to domain service AssignmentsService
    const assignment = await this.assignmentsService.createAssignment(
      context.schoolId,
      {
        classId: args.classId,
        subjectId: args.subjectId,
        title: args.topic,
        description: args.description ?? 'Generated by AI Assistant',
        dueDate: dueDateObj.toISOString(),
        maxMarks: args.totalMarks ?? 100,
        staffId: staff.id,
      },
      staff.id,
    );

    return {
      resourceId: assignment.id,
      resourceType: 'Assignment',
      status: 'CREATED',
      assignmentId: assignment.id,
      classId: args.classId,
      subjectId: args.subjectId,
    };
  }

  async verify(
    context: AgentToolExecutionContext,
    args: CreateAssignmentArgs,
    result: AgentHandlerResult,
  ): Promise<void> {
    const assignmentId = (result.assignmentId ?? result.resourceId) as
      string | undefined;
    if (!assignmentId) {
      throw new Error(AGENT_ERRORS.ACTION_VERIFICATION_FAILED);
    }

    const assignment = await this.assignmentsService.getAssignmentById(
      context.schoolId,
      assignmentId,
    );

    if (
      !assignment ||
      assignment.schoolId !== context.schoolId ||
      assignment.classId !== args.classId ||
      assignment.subjectId !== args.subjectId ||
      assignment.title !== args.topic
    ) {
      throw new Error(AGENT_ERRORS.ACTION_VERIFICATION_FAILED);
    }

    // Verify staff ownership matches authenticated user's staff profile (fail-closed)
    const staff = await this.assignmentsService.getStaffProfileByUserId(
      context.schoolId,
      context.userId,
    );
    if (!staff || assignment.staffId !== staff.id) {
      throw new Error(AGENT_ERRORS.ACTION_VERIFICATION_FAILED);
    }
  }

  async reconcile(
    context: AgentToolExecutionContext,
    args: CreateAssignmentArgs,
  ): Promise<ReconciliationResult> {
    const staff = await this.assignmentsService.getStaffProfileByUserId(
      context.schoolId,
      context.userId,
    );
    if (!staff) {
      return {
        status: 'NOT_APPLIED',
        reason: `Authenticated teacher staff profile not found for user ${context.userId} in school ${context.schoolId}`,
      };
    }

    const existing = await this.assignmentsService.findAssignmentByDetails(
      context.schoolId,
      {
        classId: args.classId,
        subjectId: args.subjectId,
        title: args.topic,
        staffId: staff.id,
      },
    );

    if (existing) {
      return {
        status: 'APPLIED',
        result: {
          resourceId: existing.id,
          resourceType: 'Assignment',
          status: 'CREATED',
          assignmentId: existing.id,
          classId: existing.classId,
          subjectId: existing.subjectId,
        },
      };
    }

    return {
      status: 'NOT_APPLIED',
      reason: `No assignment titled "${args.topic}" found for class ${args.classId}, subject ${args.subjectId}, and staff ${staff.id}`,
    };
  }
}
