"use client";

import React, { useRef, useState, useEffect, useMemo } from "react";
import { Printer, X, FileText, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/Button";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";

interface PrintableQuestionPaperModalProps {
  isOpen: boolean;
  onClose: () => void;
  paperContent: string;
  grade?: string;
  subject?: string;
  totalMarks?: number;
  duration?: string;
  schoolName?: string;
  board?: string;
}

export default function PrintableQuestionPaperModal({
  isOpen,
  onClose,
  paperContent,
  grade = "Class 10",
  subject = "Mathematics",
  totalMarks = 80,
  duration = "3 Hours",
  schoolName = "Sunrise Public School",
  board = "CBSE",
}: PrintableQuestionPaperModalProps) {
  const contentRef = useRef<HTMLDivElement>(null);
  const [customSchoolName, setCustomSchoolName] = useState(schoolName || "Sunrise Public School");
  const [examTitle, setExamTitle] = useState("Summative Assessment Evaluation • Academic Session 2026–27");

  useEffect(() => {
    if (schoolName) {
      setCustomSchoolName(schoolName);
    }
  }, [schoolName]);

  // Dynamically extract any specific exam title generated by AI (e.g., "STATE BOARD EXAMINATION (2024 - 2025)")
  useEffect(() => {
    if (paperContent) {
      const titleMatch = paperContent.match(/^#\s+([^\n]+)/);
      if (titleMatch && titleMatch[1]) {
        const extracted = titleMatch[1].trim();
        if (
          !extracted.toLowerCase().includes(customSchoolName.toLowerCase()) &&
          !customSchoolName.toLowerCase().includes(extracted.toLowerCase())
        ) {
          setExamTitle(extracted);
        }
      }
    }
  }, [paperContent, customSchoolName]);

  // Strip duplicate preamble metadata so questions start immediately below the formal letterhead
  const cleanBodyContent = useMemo(() => {
    if (!paperContent) return "";

    // 1. If the paper has instructions or sections, start cleanly from the first instruction / section
    const match = paperContent.match(
      /(?:^|\n)(#{1,4}\s*(?:General\s+Instructions?|Instructions?|SECTION\s+[A-Z]|Part\s+[A-Z]|Section\s+\d))/i
    );
    if (match && match.index !== undefined) {
      return paperContent.slice(match.index).trim();
    }

    // 2. Fallback: strip leading titles, metadata tables, duplicate parameters, and horizontal rules
    let content = paperContent;
    content = content.replace(/^#+\s+[^\n]+\n*/gi, "");
    content = content.replace(
      /^(?:\*{1,2}|_{1,2})?(?:Subject|Grade|Class|Max(?:imum)?\s*Marks|Time(?:\s*Allowed)?|Duration|Coverage|Board|Affiliated)[^\n]+\n*/gim,
      ""
    );
    content = content.replace(/^[|\s:-]+\|[^\n]+\n*/gm, "");
    content = content.replace(/^---+$\n*/gm, "");
    return content.trim();
  }, [paperContent]);

  // Split cleanBodyContent into Question Paper and Marking Scheme / Answer Key
  const { questionPaperContent, answerKeyContent } = useMemo(() => {
    if (!cleanBodyContent) {
      return { questionPaperContent: "", answerKeyContent: "" };
    }

    // Comprehensive regex to find the start of Marking Scheme / Answer Key
    const answerKeyRegex = /(?:^|\n)(?:---+|\*\*\*+)?\s*(#{1,3}\s*(?:📝\s*)?(?:STEP-BY-STEP\s+)?(?:MARKING\s+SCHEME|ANSWER\s+KEY|SOLUTIONS?|SCORING\s+KEY|EVALUATION\s+SCHEME|ANSWERS\b)[^\n]*)/i;
    const match = cleanBodyContent.match(answerKeyRegex);

    if (match && match.index !== undefined) {
      const qp = cleanBodyContent.slice(0, match.index).trim();
      const ak = cleanBodyContent.slice(match.index).trim();
      return {
        questionPaperContent: qp,
        answerKeyContent: ak,
      };
    }

    return {
      questionPaperContent: cleanBodyContent,
      answerKeyContent: "",
    };
  }, [cleanBodyContent]);

  // Custom typography components for ReactMarkdown to guarantee crisp word spacing & layout
  const printMarkdownComponents = useMemo(
    () => ({
      h1: ({ node, children, ...props }: any) => {
        const text = typeof children === "string" ? children : Array.isArray(children) ? children.join("") : "";
        const isAnswerKeyHeading = /marking\s*scheme|answer\s*key/i.test(text);
        return (
          <h1
            style={{
              fontSize: "1.25rem",
              fontWeight: 800,
              color: "#0F172A",
              marginTop: isAnswerKeyHeading ? "1rem" : "1.25rem",
              marginBottom: "0.6rem",
              wordSpacing: "0.06em",
              borderBottom: "1.5px solid #CBD5E1",
              paddingBottom: "0.3rem",
              pageBreakAfter: "avoid",
              pageBreakBefore: isAnswerKeyHeading ? "always" : undefined,
              breakBefore: isAnswerKeyHeading ? "page" : undefined,
            }}
            {...props}
          >
            {children}
          </h1>
        );
      },
      h2: ({ node, ...props }: any) => (
        <h2
          style={{
            fontSize: "1.1rem",
            fontWeight: 700,
            color: "#1E293B",
            marginTop: "1.1rem",
            marginBottom: "0.45rem",
            wordSpacing: "0.06em",
            borderBottom: "1px solid #E2E8F0",
            paddingBottom: "0.25rem",
            pageBreakAfter: "avoid",
          }}
          {...props}
        />
      ),
      h3: ({ node, ...props }: any) => (
        <h3
          style={{
            fontSize: "1rem",
            fontWeight: 700,
            color: "#334155",
            marginTop: "0.9rem",
            marginBottom: "0.35rem",
            wordSpacing: "0.06em",
            pageBreakAfter: "avoid",
          }}
          {...props}
        />
      ),
      p: ({ node, ...props }: any) => (
        <p
          style={{
            marginBottom: "0.75rem",
            lineHeight: 1.7,
            wordSpacing: "0.06em",
          }}
          {...props}
        />
      ),
      ol: ({ node, ...props }: any) => (
        <ol
          style={{
            paddingLeft: "1.75rem",
            margin: "0.6rem 0",
            listStyleType: "decimal",
            wordSpacing: "0.06em",
          }}
          {...props}
        />
      ),
      ul: ({ node, ...props }: any) => (
        <ul
          style={{
            paddingLeft: "1.75rem",
            margin: "0.6rem 0",
            listStyleType: "disc",
            wordSpacing: "0.06em",
          }}
          {...props}
        />
      ),
      li: ({ node, ...props }: any) => (
        <li
          style={{
            marginBottom: "0.45rem",
            lineHeight: 1.65,
            wordSpacing: "0.06em",
            pageBreakInside: "avoid",
          }}
          {...props}
        />
      ),
      table: ({ node, ...props }: any) => (
        <table
          style={{
            width: "100%",
            borderCollapse: "collapse",
            margin: "1rem 0",
            fontSize: "0.85rem",
            border: "1px solid #94A3B8",
            wordSpacing: "0.05em",
            pageBreakInside: "avoid",
          }}
          {...props}
        />
      ),
      thead: ({ node, ...props }: any) => <thead style={{ background: "#F1F5F9" }} {...props} />,
      th: ({ node, ...props }: any) => (
        <th
          style={{
            padding: "0.5rem 0.75rem",
            border: "1px solid #94A3B8",
            fontWeight: 700,
            textAlign: "left",
            color: "#0F172A",
            wordSpacing: "0.05em",
            background: "#F1F5F9",
          }}
          {...props}
        />
      ),
      td: ({ node, ...props }: any) => (
        <td
          style={{
            padding: "0.5rem 0.75rem",
            border: "1px solid #94A3B8",
            verticalAlign: "top",
            lineHeight: 1.55,
            wordSpacing: "0.05em",
          }}
          {...props}
        />
      ),
      strong: ({ node, ...props }: any) => (
        <strong style={{ fontWeight: 700, color: "#0F172A" }} {...props} />
      ),
      blockquote: ({ node, ...props }: any) => (
        <blockquote
          style={{
            borderLeft: "3px solid #64748B",
            background: "#F8FAFC",
            padding: "0.5rem 0.85rem",
            margin: "0.75rem 0",
            color: "#334155",
            fontSize: "0.85rem",
            wordSpacing: "0.06em",
            pageBreakInside: "avoid",
          }}
          {...props}
        />
      ),
      code: ({ node, ...props }: any) => (
        <code
          style={{
            background: "#F1F5F9",
            color: "#0F172A",
            padding: "0.15rem 0.35rem",
            borderRadius: "4px",
            fontSize: "0.875em",
            fontFamily: "monospace",
          }}
          {...props}
        />
      ),
    }),
    []
  );

  if (!isOpen) return null;

  // Isolated print function creating a dedicated, flawless multi-page A4 print context
  const handlePrint = () => {
    const printElement = document.getElementById("printable-exam-sheet");
    if (!printElement) {
      window.print();
      return;
    }

    const existingIframe = document.getElementById("print-iframe");
    if (existingIframe) {
      existingIframe.remove();
    }

    const iframe = document.createElement("iframe");
    iframe.id = "print-iframe";
    iframe.style.position = "fixed";
    iframe.style.right = "0";
    iframe.style.bottom = "0";
    iframe.style.width = "0";
    iframe.style.height = "0";
    iframe.style.border = "0";
    document.body.appendChild(iframe);

    const doc = iframe.contentWindow?.document;
    if (!doc) {
      window.print();
      return;
    }

    doc.open();
    doc.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${customSchoolName} - Examination Paper</title>
          <meta charset="utf-8" />
          <style>
            @page {
              size: A4 portrait;
              margin: 15mm 15mm 18mm 15mm;
            }
            * {
              box-sizing: border-box;
              -webkit-print-color-adjust: exact !important;
              print-color-adjust: exact !important;
            }
            body {
              font-family: 'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              color: #0F172A;
              background: #FFFFFF;
              margin: 0;
              padding: 0;
              font-size: 10.5pt;
              line-height: 1.7;
              word-spacing: 0.06em;
              letter-spacing: 0.01em;
            }
            h1, h2, h3, h4, h5, h6 {
              color: #0F172A;
              page-break-after: avoid;
              break-after: avoid;
            }
            h1 {
              font-size: 14pt;
              font-weight: 800;
              margin-top: 16pt;
              margin-bottom: 8pt;
              border-bottom: 1.5pt solid #CBD5E1;
              padding-bottom: 4pt;
            }
            h2 {
              font-size: 12.5pt;
              font-weight: 700;
              margin-top: 14pt;
              margin-bottom: 6pt;
              border-bottom: 1pt solid #E2E8F0;
              padding-bottom: 3pt;
            }
            h3 {
              font-size: 11.5pt;
              font-weight: 700;
              margin-top: 12pt;
              margin-bottom: 5pt;
            }
            p {
              margin-top: 0;
              margin-bottom: 7pt;
              line-height: 1.7;
              word-spacing: 0.06em;
            }
            ol, ul {
              margin-top: 0;
              margin-bottom: 8pt;
              padding-left: 20pt;
              line-height: 1.7;
              word-spacing: 0.06em;
            }
            li {
              margin-bottom: 5pt;
              line-height: 1.65;
              word-spacing: 0.06em;
              page-break-inside: avoid;
              break-inside: avoid;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin: 10pt 0;
              font-size: 9.5pt;
              page-break-inside: avoid;
              break-inside: avoid;
            }
            th, td {
              border: 1pt solid #94A3B8;
              padding: 5pt 8pt;
              text-align: left;
              vertical-align: top;
              word-spacing: 0.05em;
            }
            th {
              background-color: #F1F5F9 !important;
              font-weight: 700;
              color: #0F172A;
            }
            blockquote {
              border-left: 3pt solid #64748B;
              background: #F8FAFC !important;
              padding: 5pt 10pt;
              margin: 8pt 0;
              color: #334155;
              font-size: 9.5pt;
              page-break-inside: avoid;
              break-inside: avoid;
            }
            .page-break,
            .page-break-container {
              page-break-before: always !important;
              break-before: page !important;
              clear: both !important;
              display: block !important;
            }
            .no-print {
              display: none !important;
            }
          </style>
        </head>
        <body>
          ${printElement.innerHTML}
        </body>
      </html>
    `);
    doc.close();

    setTimeout(() => {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
    }, 300);
  };

  return (
    <div
      className="printable-modal-overlay"
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 9999,
        background: "rgba(15, 23, 42, 0.75)",
        backdropFilter: "blur(6px)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "1rem",
      }}
    >
      <style>{`
        @media print {
          @page {
            size: A4 portrait;
            margin: 15mm 15mm 18mm 15mm;
          }
          html, body {
            height: auto !important;
            min-height: 100% !important;
            overflow: visible !important;
            background: #FFFFFF !important;
            margin: 0 !important;
            padding: 0 !important;
          }
          body * {
            visibility: hidden !important;
          }
          .printable-modal-overlay,
          .printable-modal-card,
          .printable-scroll-wrapper {
            position: static !important;
            display: block !important;
            max-width: 100% !important;
            max-height: none !important;
            height: auto !important;
            width: 100% !important;
            overflow: visible !important;
            border: none !important;
            box-shadow: none !important;
            background: #FFFFFF !important;
            padding: 0 !important;
            margin: 0 !important;
          }
          #printable-exam-sheet {
            visibility: visible !important;
            position: static !important;
            display: block !important;
            width: 100% !important;
            max-width: 100% !important;
            height: auto !important;
            padding: 0 !important;
            margin: 0 !important;
            border: none !important;
            box-shadow: none !important;
            background: #FFFFFF !important;
            color: #000000 !important;
            overflow: visible !important;
            word-spacing: 0.08em !important;
            letter-spacing: 0.015em !important;
            line-height: 1.75 !important;
          }
          #printable-exam-sheet * {
            visibility: visible !important;
            word-spacing: 0.08em !important;
          }
          .page-break,
          .page-break-container {
            page-break-before: always !important;
            break-before: page !important;
            clear: both !important;
            display: block !important;
          }
          .no-print {
            display: none !important;
          }
        }
      `}</style>

      <div
        className="printable-modal-card"
        style={{
          background: "var(--bg-surface)",
          borderRadius: "var(--radius-xl)",
          width: "100%",
          maxWidth: "920px",
          maxHeight: "92vh",
          display: "flex",
          flexDirection: "column",
          boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.4)",
          border: "1px solid var(--border-default)",
          overflow: "hidden",
        }}
      >
        {/* Modal Action Header (Excluded in Print) */}
        <div
          className="no-print"
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            padding: "1rem 1.5rem",
            borderBottom: "1px solid var(--border-default)",
            background: "var(--bg-app)",
            flexWrap: "wrap",
            gap: "0.75rem",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
            <FileText size={18} style={{ color: "var(--brand-primary)" }} />
            <span style={{ fontWeight: 700, fontSize: "var(--text-sm)" }}>
              Official Printable Examination Paper
            </span>
            <span
              style={{
                fontSize: "11px",
                padding: "0.2rem 0.5rem",
                borderRadius: "var(--radius-full)",
                background: "rgba(99, 102, 241, 0.12)",
                color: "var(--brand-primary)",
                fontWeight: 600,
              }}
            >
              A4 Format Ready
            </span>
          </div>

          <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
            {/* Quick School Letterhead Edit */}
            <div style={{ display: "flex", alignItems: "center", gap: "0.35rem" }}>
              <span style={{ fontSize: "12px", color: "var(--text-secondary)", fontWeight: 600 }}>
                School:
              </span>
              <input
                type="text"
                value={customSchoolName}
                onChange={(e) => setCustomSchoolName(e.target.value)}
                placeholder="Enter School Name"
                style={{
                  fontSize: "12px",
                  padding: "0.3rem 0.6rem",
                  borderRadius: "var(--radius-md)",
                  border: "1px solid var(--border-default)",
                  background: "var(--bg-surface)",
                  color: "var(--text-primary)",
                  fontWeight: 600,
                  width: "180px",
                }}
                title="Edit school letterhead name before printing"
              />
            </div>

            <Button
              size="sm"
              onClick={handlePrint}
              style={{ display: "flex", alignItems: "center", gap: "0.4rem" }}
            >
              <Printer size={15} />
              Print / Save as PDF
            </Button>
            <button
              onClick={onClose}
              style={{
                background: "transparent",
                border: "none",
                cursor: "pointer",
                color: "var(--text-secondary)",
                padding: "0.35rem",
                borderRadius: "var(--radius-md)",
              }}
              title="Close modal"
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Scrollable Printable Paper Container */}
        <div
          className="printable-scroll-wrapper"
          style={{
            flex: 1,
            overflowY: "auto",
            padding: "2rem",
            background: "var(--bg-app)",
          }}
        >
          <div
            id="printable-exam-sheet"
            ref={contentRef}
            style={{
              background: "#FFFFFF",
              color: "#1E293B",
              padding: "2.5rem 3rem",
              borderRadius: "var(--radius-lg)",
              border: "1px solid #CBD5E1",
              boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
              fontFamily: "'Inter', system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
              lineHeight: 1.75,
              wordSpacing: "0.06em",
              letterSpacing: "0.01em",
            }}
          >
            {/* Formal Examination Letterhead */}
            <div
              style={{
                textAlign: "center",
                borderBottom: "2px solid #0F172A",
                paddingBottom: "1rem",
                marginBottom: "1.25rem",
              }}
            >
              <div
                style={{
                  fontSize: "1.5rem",
                  fontWeight: 900,
                  letterSpacing: "0.03em",
                  color: "#0F172A",
                  textTransform: "uppercase",
                  wordSpacing: "0.08em",
                }}
              >
                {customSchoolName}
              </div>
              <div
                style={{
                  fontSize: "0.95rem",
                  fontWeight: 700,
                  color: "#1E293B",
                  marginTop: "0.25rem",
                  wordSpacing: "0.05em",
                }}
              >
                {examTitle}
              </div>
              <div
                style={{
                  fontSize: "0.8rem",
                  fontWeight: 500,
                  color: "#64748B",
                  marginTop: "0.15rem",
                  wordSpacing: "0.04em",
                }}
              >
                Affiliated to {board.toUpperCase().includes("BOARD") ? board : `${board} Board`} | Nursery – Class X
              </div>
            </div>

            {/* Compact, Clean Candidate Credentials Bar */}
            <div
              style={{
                border: "1.5px solid #0F172A",
                borderRadius: "6px",
                padding: "0.65rem 1rem",
                marginBottom: "1.5rem",
                fontSize: "0.85rem",
                background: "#F8FAFC",
                wordSpacing: "0.05em",
              }}
            >
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "1.2fr 1.2fr 1fr 1fr",
                  gap: "0.5rem",
                  alignItems: "center",
                  paddingBottom: "0.45rem",
                  borderBottom: "1px dashed #CBD5E1",
                }}
              >
                <div>
                  <strong style={{ color: "#0F172A" }}>Class & Sec: </strong>
                  <span>{grade} — _____</span>
                </div>
                <div>
                  <strong style={{ color: "#0F172A" }}>Subject: </strong>
                  <span>{subject}</span>
                </div>
                <div>
                  <strong style={{ color: "#0F172A" }}>Max Marks: </strong>
                  <span>{totalMarks}</span>
                </div>
                <div>
                  <strong style={{ color: "#0F172A" }}>Time Allowed: </strong>
                  <span>{duration}</span>
                </div>
              </div>

              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "2fr 1fr 1fr",
                  gap: "0.75rem",
                  alignItems: "center",
                  paddingTop: "0.45rem",
                }}
              >
                <div>
                  <strong style={{ color: "#0F172A" }}>Candidate Name: </strong>
                  <span>___________________________________</span>
                </div>
                <div>
                  <strong style={{ color: "#0F172A" }}>Roll No: </strong>
                  <span>_________________</span>
                </div>
                <div style={{ textAlign: "right" }}>
                  <strong style={{ color: "#0F172A" }}>Date: </strong>
                  <span>______________</span>
                </div>
              </div>
            </div>

            {/* ─── PART 1: STUDENT QUESTION PAPER ─── */}
            <div className="question-paper-section">
              <div
                className="prose"
                style={{
                  fontSize: "0.95rem",
                  color: "#1E293B",
                  wordSpacing: "0.06em",
                }}
              >
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  rehypePlugins={[rehypeRaw]}
                  components={printMarkdownComponents}
                >
                  {questionPaperContent}
                </ReactMarkdown>
              </div>

              {/* Student & Invigilator Verification Footer (Placed directly at the end of the Question Paper) */}
              <div
                className="exam-verification-footer"
                style={{
                  marginTop: "2.5rem",
                  paddingTop: "1.25rem",
                  borderTop: "1.5px solid #0F172A",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "flex-end",
                  fontSize: "0.85rem",
                  color: "#334155",
                  wordSpacing: "0.05em",
                  pageBreakInside: "avoid",
                  breakInside: "avoid",
                }}
              >
                <div>
                  <div style={{ fontWeight: 600 }}>Date of Examination: ______________</div>
                  <div style={{ marginTop: "0.5rem" }}>Candidate Signature: _______________________</div>
                </div>
                <div style={{ textAlign: "center", fontSize: "0.75rem", color: "#64748B", fontWeight: 700, letterSpacing: "0.05em" }}>
                  *** END OF QUESTION PAPER ***
                </div>
                <div style={{ textAlign: "right" }}>
                  <div style={{ fontWeight: 600 }}>Room / Hall Number: _________</div>
                  <div style={{ marginTop: "0.5rem" }}>Invigilator Signature: _______________________</div>
                </div>
              </div>
            </div>

            {/* ─── PART 2: EVALUATOR MARKING SCHEME & ANSWER KEY (NEW PAGE) ─── */}
            {answerKeyContent ? (
              <div
                className="page-break-container"
                style={{
                  pageBreakBefore: "always",
                  breakBefore: "page",
                  clear: "both",
                  marginTop: "3rem",
                }}
              >
                {/* Visual Divider in On-Screen Modal (hidden in print) */}
                <div
                  className="no-print"
                  style={{
                    margin: "2.5rem -3rem",
                    padding: "0.85rem 2rem",
                    background: "#F1F5F9",
                    borderTop: "2px dashed #94A3B8",
                    borderBottom: "2px dashed #94A3B8",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    gap: "0.75rem",
                    color: "#475569",
                    fontWeight: 700,
                    fontSize: "0.8rem",
                    letterSpacing: "0.06em",
                    textTransform: "uppercase",
                  }}
                >
                  <span>✂</span>
                  <span>Official Page Break: Marking Scheme & Answer Key Starts on New Page</span>
                  <span>✂</span>
                </div>

                {/* Answer Key Formal Letterhead */}
                <div
                  style={{
                    textAlign: "center",
                    borderBottom: "2px solid #0F172A",
                    paddingBottom: "0.85rem",
                    marginBottom: "1.25rem",
                    paddingTop: "0.5rem",
                  }}
                >
                  <div
                    style={{
                      fontSize: "1.3rem",
                      fontWeight: 900,
                      letterSpacing: "0.03em",
                      color: "#0F172A",
                      textTransform: "uppercase",
                      wordSpacing: "0.08em",
                    }}
                  >
                    {customSchoolName}
                  </div>
                  <div
                    style={{
                      display: "inline-block",
                      marginTop: "0.35rem",
                      padding: "0.25rem 0.85rem",
                      borderRadius: "4px",
                      background: "#0F172A",
                      color: "#FFFFFF",
                      fontWeight: 800,
                      fontSize: "0.8rem",
                      letterSpacing: "0.08em",
                      textTransform: "uppercase",
                    }}
                  >
                    Confidential — Evaluator Marking Scheme & Scoring Key
                  </div>
                  <div
                    style={{
                      fontSize: "0.85rem",
                      fontWeight: 600,
                      color: "#334155",
                      marginTop: "0.35rem",
                      wordSpacing: "0.05em",
                    }}
                  >
                    {grade} • {subject} • Max. Marks: {totalMarks} • Time Allowed: {duration}
                  </div>
                </div>

                {/* Answer Key Markdown Body */}
                <div
                  className="prose"
                  style={{
                    fontSize: "0.95rem",
                    color: "#1E293B",
                    wordSpacing: "0.06em",
                  }}
                >
                  <ReactMarkdown
                    remarkPlugins={[remarkGfm]}
                    rehypePlugins={[rehypeRaw]}
                    components={printMarkdownComponents}
                  >
                    {answerKeyContent}
                  </ReactMarkdown>
                </div>

                {/* Evaluator Verification Sign-Off Footer */}
                <div
                  style={{
                    marginTop: "2.5rem",
                    paddingTop: "1.25rem",
                    borderTop: "1.5px solid #0F172A",
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "flex-end",
                    fontSize: "0.85rem",
                    color: "#334155",
                    wordSpacing: "0.05em",
                    pageBreakInside: "avoid",
                    breakInside: "avoid",
                  }}
                >
                  <div>
                    <div style={{ fontWeight: 600 }}>Examiner / Evaluator Name: _______________________</div>
                    <div style={{ marginTop: "0.5rem" }}>Evaluator Signature: _______________________</div>
                  </div>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontWeight: 600 }}>Date of Evaluation: ______________</div>
                    <div style={{ marginTop: "0.5rem", fontWeight: 700, color: "#0F172A" }}>
                      Total Verified Marks: _____ / {totalMarks}
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  );
}
