export interface AgentExecutionContext {
  userId: string;
  role: string;
  schoolId: string;
  isGlobal?: boolean;
}

export interface AgentActionResult {
  actionId: string;
  status: string;
  result?: any;
  failureReason?: string;
  explanation?: string;
}

export const AGENT_ERRORS = {
  ACTION_NOT_FOUND: 'ACTION_NOT_FOUND',
  ACTION_NOT_AUTHORIZED: 'ACTION_NOT_AUTHORIZED',
  ACTION_TENANT_MISMATCH: 'ACTION_TENANT_MISMATCH',
  ACTION_RESOURCE_FORBIDDEN: 'ACTION_RESOURCE_FORBIDDEN',
  ACTION_CONFIRMATION_REQUIRED: 'ACTION_CONFIRMATION_REQUIRED',
  ACTION_EXPIRED: 'ACTION_EXPIRED',
  ACTION_ALREADY_EXECUTED: 'ACTION_ALREADY_EXECUTED',
  ACTION_INVALID_ARGUMENTS: 'ACTION_INVALID_ARGUMENTS',
  ACTION_POLICY_DENIED: 'ACTION_POLICY_DENIED',
  ACTION_EXECUTION_FAILED: 'ACTION_EXECUTION_FAILED',
  ACTION_VERIFICATION_FAILED: 'ACTION_VERIFICATION_FAILED',
} as const;
